<a href="https://colab.research.google.com/github/cleysonl/Tensorflow2.0/blob/master/ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensorflow 2.0

In [1]:
!pip install tensorflow-gpu==2.0.0-alpha0

     |████████████████████████████████| 332.1MB 101kB/s 
     |████████████████████████████████| 3.0MB 26.3MB/s 
     |████████████████████████████████| 419kB 28.7MB/s 


In [0]:
import tensorflow as tf
import numpy as np

In [4]:
tf.__version__

'2.0.0-alpha0'

##Constants

### Defining a Constant

In [0]:
tensor_20 = tf.constant([[23,4],[32,51]])

In [6]:
tensor_20

<tf.Tensor: id=0, shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]], dtype=int32)>

### Getting the value of a constant

In [7]:
tensor_20.numpy()

array([[23,  4],
       [32, 51]], dtype=int32)

In [0]:
numpy_tensor = np.array([[23,4],[32,51]])

In [0]:
tensor_from_numpy = tf.constant(numpy_tensor)

In [10]:
tensor_from_numpy

<tf.Tensor: id=3, shape=(2, 2), dtype=int64, numpy=
array([[23,  4],
       [32, 51]])>

## Variables

###Defining a variable

In [11]:
tf2_variable = tf.Variable([[1.,2.,3.],[4.,5.,6.]])
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

### Getting the value of a variable

In [13]:
tf2_variable.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

### Changing the value of a variable

In [14]:
tf2_variable[0,2].assign(100)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

In [15]:
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

### Operations with tensors

In [16]:
tensor = tf.constant([[1,2],[3,4]])
tensor

<tf.Tensor: id=33, shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

### Addition between a scalar and a tensor

In [17]:
tensor + 2

<tf.Tensor: id=36, shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6]], dtype=int32)>

### Multiplication between a scalar and a tensor

In [18]:
tensor *5

<tf.Tensor: id=39, shape=(2, 2), dtype=int32, numpy=
array([[ 5, 10],
       [15, 20]], dtype=int32)>

### Using Numpy functions on Tensorflow tenors

In [19]:
np.square(tensor)

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [20]:
np.sqrt(tensor)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [21]:
np.exp(tensor)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

### Dot product between two tensors

In [24]:
np.dot(tensor,tensor_20)

array([[ 87, 106],
       [197, 216]], dtype=int32)

## Strings

In [25]:
tf_string = tf.constant('Tensorflow')
tf_string

<tf.Tensor: id=66, shape=(), dtype=string, numpy=b'Tensorflow'>

### Simple string operations

In [30]:
tf.strings.length(tf_string)

<tf.Tensor: id=70, shape=(), dtype=int32, numpy=10>

In [31]:
tf.strings.unicode_decode(tf_string,"UTF8")

<tf.Tensor: id=75, shape=(10,), dtype=int32, numpy=array([ 84, 101, 110, 115, 111, 114, 102, 108, 111, 119], dtype=int32)>

### Storing arrays of strings

In [0]:
tf_string_array = tf.constant(["Tensorflow","Deep Learning","A1"])

In [33]:
for string in tf_string_array:
  print(string)

tf.Tensor(b'Tensorflow', shape=(), dtype=string)
tf.Tensor(b'Deep Learning', shape=(), dtype=string)
tf.Tensor(b'A1', shape=(), dtype=string)
