<a href="https://colab.research.google.com/github/cleysonl/Tensorflow2.0/blob/master/ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensorflow 2.0

In [1]:
!pip install tensorflow-gpu==2.0.0-alpha0

     |████████████████████████████████| 332.1MB 101kB/s 
     |████████████████████████████████| 3.0MB 26.3MB/s 
     |████████████████████████████████| 419kB 28.7MB/s 


In [0]:
import tensorflow as tf
import numpy as np

In [4]:
tf.__version__

'2.0.0-alpha0'

##Constants

### Defining a Constant

In [0]:
tensor_20 = tf.constant([[23,4],[32,51]])

In [6]:
tensor_20

<tf.Tensor: id=0, shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]], dtype=int32)>

### Getting the value of a constant

In [7]:
tensor_20.numpy()

array([[23,  4],
       [32, 51]], dtype=int32)

In [0]:
numpy_tensor = np.array([[23,4],[32,51]])

In [0]:
tensor_from_numpy = tf.constant(numpy_tensor)

In [10]:
tensor_from_numpy

<tf.Tensor: id=3, shape=(2, 2), dtype=int64, numpy=
array([[23,  4],
       [32, 51]])>

## Variables

###Defining a variable

In [11]:
tf2_variable = tf.Variable([[1.,2.,3.],[4.,5.,6.]])
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

### Getting the value of a variable

In [13]:
tf2_variable.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

### Changing the value of a variable

In [14]:
tf2_variable[0,2].assign(100)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

In [15]:
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>