<a href="https://colab.research.google.com/github/cleysonl/Tensorflow2.0/blob/master/Tensorflow_2_0_CC_CLL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install tensorflow-gpu==2.0.0

In [2]:
import tensorflow as tf
print(tf.__version__)

2.0.0


## **1. Basics**

### **Tensors**

In [3]:
#constant tensor
x = tf.constant([[3,4],[2,1]])
print(x)

tf.Tensor(
[[3 4]
 [2 1]], shape=(2, 2), dtype=int32)


In [4]:
# Convert the value to numpy array
x.numpy()

array([[3, 4],
       [2, 1]], dtype=int32)

In [5]:
# As numpy array, it has the attribute dtype and shape:
print('dtype:', x.dtype)
print('shape:', x.shape)


dtype: <dtype: 'int32'>
shape: (2, 2)


In [6]:
# Arrays of ones an zeros
print(tf.ones(shape=(2,1)))
print(tf.zeros(shape=(2,1)))

tf.Tensor(
[[1.]
 [1.]], shape=(2, 1), dtype=float32)
tf.Tensor(
[[0.]
 [0.]], shape=(2, 1), dtype=float32)


### **Random constant tensors**

In [7]:
tf.random.normal(shape=(2,2),mean =0., stddev = 1.)

<tf.Tensor: id=12, shape=(2, 2), dtype=float32, numpy=
array([[ 0.17656726,  0.7821833 ],
       [-0.39302078, -1.1789931 ]], dtype=float32)>

In [8]:
tf.random.uniform(shape=(2,2), minval=0, maxval=10, dtype='int32')

<tf.Tensor: id=16, shape=(2, 2), dtype=int32, numpy=
array([[3, 9],
       [6, 2]], dtype=int32)>

### **Variables**

In [9]:
initial_value = tf.random.normal(shape=(2,2))
a = tf.Variable(initial_value)
print(a)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-0.7218575,  0.7998897],
       [-0.833387 ,  2.1405194]], dtype=float32)>


In [11]:
new_value = tf.random.normal(shape=(2,2))
a.assign(new_value)
print(a)
for i in range(2):
  for j in range(2):
    assert a[i,j]==new_value[i,j]
print(a)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 0.12952878, -2.17104   ],
       [-1.3478723 , -0.48950976]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 0.12952878, -2.17104   ],
       [-1.3478723 , -0.48950976]], dtype=float32)>


In [12]:
added_value = tf.random.normal(shape=(2,2))
a.assign_add(added_value)
print(a)
for i in range(2):
  for j in range(2):
    assert a[i,j]== new_value[i,j] + added_value[i,j]
print(a)    

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-0.68735516, -0.46691883],
       [-1.4727607 , -0.26714143]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-0.68735516, -0.46691883],
       [-1.4727607 , -0.26714143]], dtype=float32)>


### **Doing math in TF**

In [0]:
a = tf.random.normal(shape=(2,2))
b = tf.random.normal(shape=(2,2))

c = a + b
d = tf.square(c)
e = tf.exp(d)

### **Computing gradient with** 'GradientTape'

In [14]:
a = tf.random.uniform(shape=(2,2))
b = tf. random.uniform(shape=(2,2))

a= tf.Variable(a)

with tf.GradientTape() as tape:
  c = tf.sqrt(tf.square(a) + tf.sqrt(b))
  dc_da = tape.gradient(c,a)
  print(dc_da)

tf.Tensor(
[[0.6406857  0.6852122 ]
 [0.47625476 0.40463915]], shape=(2, 2), dtype=float32)


In [15]:
# High-order derivatives with nesting tapes
with tf.GradientTape() as outer_tape:
  with tf. GradientTape() as tape:
    c = tf.sqrt(tf.square(a) + tf.square(b))
    dc_da = tape.gradient(c,a)
  dc2_da2= outer_tape.gradient(dc_da,a)
  print(dc2_da2)

tf.Tensor(
[[0.3601032  0.02922845]
 [0.7155734  0.97444296]], shape=(2, 2), dtype=float32)
